task6
aplachka/react pull request #6
Opened 2020-05-22 12:18 UTC by aplachka

2020-05-25 07:29 UTC, dima19972525 commented
![image](https://user-images.githubusercontent.com/23092460/82789150-813de900-9e72-11ea-9f08-dcafbc186ec7.png)
Почему уже есть созданная 7 ветка с готовым таском к 7 заданию?

2020-05-25 08:14 UTC, dima19972525 commented
Есть проблема с апдейтом стейта карточек. Редактирую карточку -> сохраняю изменения -> нажимаю на кнопку "Удалить выбранные карточки".
Когда я смотрю на код:
```js
const CardList = (props) => {
    console.log('CARDS: ', props.cardList);
    return (
        <GridList cols={3} spacing={20}>
            {props.cardList.map((card) => (
                <GridListTile key={card.id}>
                    <MyCard
                        key={card.id}
                        title={card.caption}
                        content={card.text}
                        editAllowed={props.editAllowed}
                        onChecked={props.onChecked(card.id)}
                    />
                </GridListTile>
            ))}
        </GridList>
    );
};
```
Смотря на код, я предполагаю, что мы берем массив **cardList** и рендерим карточки используя значения этого массива (т.к. это явно указано в пропсах "content\title" и т.д.), .  Но после нажатие кнопку "Удалить выбранные карточки", массив не изменен
![image](https://user-images.githubusercontent.com/23092460/82791506-90bf3100-9e76-11ea-900b-e62c3991e23d.png)
Это путает, что вообще тогда делают пропсы "content\title".
Исправьте, пожалуйста, это.
И насчет кода 
![image](https://user-images.githubusercontent.com/23092460/82792239-c1539a80-9e77-11ea-8b31-8ae81348a1bc.png)
Можно заменить на 
```js
cards.find((v) => v.id === id).checked = checked;
```
и, обычно, стейт никогда не изменяется напрямую (без испольования setState), но бывают случаи, когда можно изменить его, как в этом коде (https://stackoverflow.com/questions/42060641/react-changing-the-state-without-using-setstate-must-avoid-it).
В данном случае свойство checked даже никак не исопльзуется в компоненьте MyCard (но оно может использоваться, т.к. у карточки есть свойство checked (которое по умолчанию false) и никак не регулируется из вне, хотя у этого свойства большой потенциал, чтобы он был контролируемым, как, например, content и т.д.).
Создайте пропс checked для компонента MyCard и подвежите к нему свойство checked

2020-05-25 08:15 UTC, dima19972525 requested changes
Поправьте изменения выше. Видны ли сейчас следующие таски?

2020-05-25 08:22 UTC, aplachka commented
> Поправьте изменения выше. Видны ли сейчас следующие таски?

Следующие таски теперь не видны

2020-05-26 09:28 UTC, dima19972525 commented
Уберите пропс id из карточки, этот пропс не нужен, вы его используете только для поиска конкретной карточке в массиве.
Вот пример как можно искать нужную карточку без пропса id
```js
<MyCard
                        title={card.caption}
                        content={card.text}
                        editAllowed={props.editAllowed}
                        onChecked={() => props.onChecked(card.id)}
                        onSubmit={() => props.onSubmit(card.id)}
                        checked={card.checked}
                    />
```

2020-05-26 09:29 UTC, dima19972525 approved these changes
Поправьте изменения выше и мерж

2020-05-26 09:29 UTC, dima19972525 commented on src/components/Main/Main.js
> +    };
Можно заменить на 
```js
        setCards(cards.map((_card) => (_card.id === card.id ? card : _card)));
```

2020-05-26 09:29 UTC, dima19972525 commented on src/components/Main/Main.js
> +    };
```js
setCards(
            cards.map((_card) =>
                _card.id === id ? { ..._card, checked } : _card,
            ),
        );
```

2020-05-26 11:59 UTC, merged